algo: "a3c"
state_dim: 27
action_dim: 1
reward_dim: 8
response_dim: 8
max_action: 150
max_buffer_size: 5000000
discount: 0.99
tau: 0.001

max_steps: 60000
test_every: 10
log_every: 10000
save_every: 100

batch_size: 128

save_model: False
use_tensorboard: True
bc_loss_coeff: 0.01

reward_service: 0.1
reward_business: 0.1
reward_cleanliness: 0.1
reward_check_in: 0.1
reward_value: 0.1
reward_rooms: 0.1
reward_location: 0.1
reward_overall: 10.0

model_path: "/results/a3c_loc/5/models/"