algo: "awac"
state_dim: 27
action_dim: 1
reward_dim: 8
response_dim: 8
max_action: 150
max_buffer_size: 5000000
discount: 0.99
tau: 0.001

max_steps: 320000
test_every: 10
log_every: 10000
save_every: 10000

batch_size: 128

save_model: True
use_tensorboard: True
bc_loss_coeff: 0.01

reward_service: 1.0
reward_business: 1.0
reward_cleanliness: 1.0
reward_check_in: 1.0
reward_value: 1.0
reward_rooms: 1.0
reward_location: 1.0
reward_overall: 100

kappa: 1.0
constrained_policy_model_path: "/results/multi_critic_a3c/10/models/"
model_path: ""
