algo: "multi_critic_awac_ddpg"
state_dim: 1044
action_dim: 1
reward_dim: 7
response_dim: 7
max_action: 150
max_buffer_size: 5000000
discount: 0.99
tau: 0.001

max_steps: 500000
test_every: 10
log_every: 20000
save_every: 2000

batch_size: 512

save_model: False
use_tensorboard: True

bc_loss_coeff: 0.01
kl_loss_coeff: 10
awac_loss_coef: 1.0

reward_service: 1
reward_business: 1
reward_cleanliness: 1
reward_check_in: 1
reward_value: 1
reward_rooms: 1
reward_location: 100

sigma: 0.1
constrained_policy_model_path: "/results/multi_critic_awac_ddpg_zc/12/models/"
